### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [m2m-solutions/M2M_LM75A#2]
Hi @m2m-solutions

we have detected that you changed the name of the library in `library.properties` from
  `M2M Solution LM75A Library`
to
  `LM75A Arduino library`
is that right?
We are introducing a change in the library manager that forbids this kind of changes and ignore the releases with the name that differs from the name registered in the library index.

Is it ok for you to keep the new name `LM75A Arduino library`? The older releases with a different name will be ignored by the library manager. In absence of an answer from you we will proceed with this proposal next week.

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 843 - 2018/01/15 15:44:11 Scraping https://github.com/m2m-solutions/M2M_LM75A.git
JOB 843 - 2018/01/15 15:44:11 Checking out tag: v1.0.0
JOB 843 - 2018/01/15 15:44:11 Release M2M Solution LM75A Library:1.0.0 already loaded, skipping
JOB 843 - 2018/01/15 15:44:11 Checking out tag: v1.0.1
JOB 843 - 2018/01/15 15:44:11 Release LM75A Arduino library:1.0.1 has wrong library name, should be M2M Solution LM75A Library
```

See also: https://github.com/arduino/Arduino/issues/7127

**Comment by bergdahl** [comment]
Yes, it is OK. Thanks for the heads up.

Regards;
/jb

---------------------------------------
Bergdahl IT AB
Jonny Bergdahl
Kapellgatan 6C
553 17  JÖNKÖPING
Sweden
Phone: +46 36 190500
Email: jonny@bergdahl.it<mailto:jonny@bergdahl.it>



15 jan. 2018 kl. 17:25 skrev Cristian Maglie <notifications@github.com<mailto:notifications@github.com>>:


Hi @m2m-solutions<https://github.com/m2m-solutions>

we have detected that you changed the name of the library in library.properties from
M2M Solution LM75A Library
to
LM75A Arduino library
is that right?
We are introducing a change in the library manager that forbids this kind of changes and ignore the releases with the name that differs from the name registered in the library index.

Is it ok for you to keep the new name LM75A Arduino library? The older releases with a different name will be ignored by the library manager. In absence of an answer from you we will proceed with this proposal next week.

See also: arduino/Arduino#7127<https://github.com/arduino/Arduino/issues/7127>

JOB 843 - 2018/01/15 15:44:11 Scraping https://github.com/m2m-solutions/M2M_LM75A.git
JOB 843 - 2018/01/15 15:44:11 Checking out tag: v1.0.0
JOB 843 - 2018/01/15 15:44:11 Release M2M Solution LM75A Library:1.0.0 already loaded, skipping
JOB 843 - 2018/01/15 15:44:11 Checking out tag: v1.0.1
JOB 843 - 2018/01/15 15:44:11 Release LM75A Arduino library:1.0.1 has wrong library name, should be M2M Solution LM75A Library


See also: arduino/Arduino#7127<https://github.com/arduino/Arduino/issues/7127>
