### ISSUE TITLE
2's complement temperature values

### ISSUE THREAD

**Issue by TimMathias** [m2m-solutions/M2M_LM75A#5]
The temperature values are in 2's complement format. See sections 7.4.3 and 7.4.4 of the [LM75A datasheet](https://www.nxp.com/docs/en/data-sheet/LM75A.pdf).

But they are being left as unsigned before converting to float in the following lines resulting in positive values for negative temperatures:
https://github.com/m2m-solutions/M2M_LM75A/blob/104d8b1bfc146bb5bf2f86fa7b710ab86ecc8af5/src/M2M_LM75A.cpp#L73
https://github.com/m2m-solutions/M2M_LM75A/blob/104d8b1bfc146bb5bf2f86fa7b710ab86ecc8af5/src/M2M_LM75A.cpp#L92
https://github.com/m2m-solutions/M2M_LM75A/blob/104d8b1bfc146bb5bf2f86fa7b710ab86ecc8af5/src/M2M_LM75A.cpp#L107

A simple fix would be to cast to a signed integer before converting to a float:
```c++
	return float(int16_t(result)) / 256.0f;
```

**Comment by bergdahl** [comment]
Please do a pull request.

**Comment by bergdahl** [comment]
Thanks!
